" PATHS

set viminfo+=n~/.vim/viminfo

" set runtimepath^=~/.vim/bundle/latexlivepreview.vim
"set packpath=~/.vim/pack/vendor

" BEPO
" plus d’infos ici : https://bepo.fr/wiki/Vim 
source ~/.vim/vimrc.bepo

" GENERAL

set smartindent
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set hlsearch "highlighting search matches
"press return to temporarily get out of the highlighted search
nnoremap <CR> :nohlsearch<CR><CR> 
set number
set foldmethod=syntax

" search down into subfolders
" set path+=** => freeze la fenetre. trop de fichiers a scanner
" set wildmenu

" browsing
let g:netrw_banner=0        " disable annoying banner
"let g:netrw_browse_split=4  " open in prior window
"let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'


" leader
let mapleader=","

" vim-latex-live-preview settings
" autocmd Filetype tex setl updatetime=1
let g:livepreview_previewer = 'open -a Preview'

" ligntline
set laststatus=2

" vimwiki
set nocompatible
filetype plugin on
syntax on
"let g:vimwiki_list = [{'path': '~/Dropbox/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
"au FileType vimwiki setlocal shiftwidth=6 tabstop=6 noexpandtab
" insert template prod
nnoremap ,pt :-1read ~/Dropbox/vimwiki/.prodtemplate.md<CR>

" spell check
set spellfile=~/.vim/spell/fr.utf-8.add,~/.vim/spell/eo.utf-8.add
map <F5> :setlocal spell! spelllang=en_us<CR>
map <F6> :setlocal spell! spelllang=fr<CR>
map <F7> :setlocal spell! spelllang=eo<CR>

" Goyo + Limelight
nnoremap <leader>gy :Goyo 90%<CR>
"Goyo 90%
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!




